### ISSUE TITLE
Connection closed on every docker build

### ISSUE THREAD

**Issue by ericchaves** [coreos/coreos-vagrant#103]
I'm using Coreos-vagrant to develop my Dockerfiles in my notebook (osx 10.9.2) where I shared my working folder with coreos so I can edit the Dockerfile with my text editor and build the image on coreos from an ssh console.

Once docker outputs that the build was successfull, connection between host and coreos is lost leaving the image untagged and having me needing to ssh into coreos a gain. ALso

In my Vagrantfile I manually upgraded it to coreos-beta. Vagrantfile and output can be found on [this gist]( https://gist.github.com/ericchaves/ec32c6a20a09f254afb5).

**UPDATE**: I also noticed that the shared folder becomes empty unless I halt/up the virtual machine again.

Any ideas on what could it be? Am I doing something wrong here?

Thanks

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1380
