### ISSUE TITLE
Connecting using port forwarding results in failed connections

### ISSUE THREAD

**Issue by hoshposh** [coreos/coreos-vagrant#121]
Attempting to use the *$expose_docker_tcp* in config.rb establishes the vagrant port-forwarding. I am then setting the *DOCKER_HOST* var to the port that is exposed to the host:
```
export DOCKER_HOST=tcp://localhost:4243
```

Attempting to invoke *docker version* results in 
```
Client version: 0.11.1
Client API version: 1.11
Go version (client): go1.2.2
Git commit (client): fb99f99
2014/06/04 09:36:42 Get http://localhost:4243/v1.11/version: EOF
```

Further digging using "curl http://localhost:4243/v1.11/version" results in:
```
curl: (52) Empty reply from server
```

It appears that the port is not being utilized by the docker service in the CoreOS vm.

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1378
