### ISSUE TITLE
feature request: rackspace provider

### ISSUE THREAD

**Issue by michaelsbradleyjr** [coreos/coreos-vagrant#130]
It would be great if this kit were expanded to include support for Vagrant's [rackspace provider-plugin](https://github.com/mitchellh/vagrant-rackspace).

I tried my hand at doing that very thing, but realized that in my noob'ness I'm missing parts of the big picture with respect to setting up the "box" correctly, etc.

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1376
