### ISSUE TITLE
coreos-cloudinit

### ISSUE THREAD

**Issue by wiliamsouza** [coreos/coreos-vagrant#137]
When coreos-cloudinit get called? It is a one-shot program only runs when the machine is first time started? I changed user-data to add a file to /etc/env.d and run vagrant reload --provision it updates the /var/lib/coreos-vagrant/vagrantfile-user-data but I need to run  sudo coreos-cloudinit --from-file /var/lib/coreos-vagrant/vagrantfile-user-data by hand to get the file created or updated.

**Comment by claytonsilva** [comment]
@wiliamsouza , nice project

i will use in my development enviroment :D

**Comment by claytonsilva** [comment]
@wiliamsouza , i adjust your user-data, and now it's running :dancers: 

https://gist.github.com/claytonsilva/6973acddea9797cbbd8f

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1372
