### ISSUE TITLE
NFS user permission to docker container from mac

### ISSUE THREAD

**Issue by Devric** [coreos/coreos-vagrant#139]
i need to share volume with a docker container, but it had no write permission to the shared volume. Within my VM i can see that the user is 501, how to make it the proper core:core user so it can be writable within docker container?

    this is the folder permission
    drwxr-xr-x 7  501   20 238 Jun 25 04:33 share   

I tried using vagrant-bindfs plugin, but a msg saying coreos does not support guest

**Comment by nballotta** [comment]
No solutions for this issue? On MacOS I've the same problem and bind-fs vagrant plugin doesn't work. 

I think that for developers, being able to write into a local mounted docker folder, would be very useful. 

Any chance to solve this problem?

**Comment by jgsqware** [comment]
Hello any update on this issue, I get exactly the same?

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1371
