### ISSUE TITLE
[question] multicast networking between containers on different hosts

### ISSUE THREAD

**Issue by defunctzombie** [coreos/coreos-vagrant#157]
Using the vagrant file I have launched 2 coreos nodes. The default network configuration creates two network devices on the hosts: enp0s3 and enp0s8.

**enp0s3** has ip 10.0.2.15 and is setup for NAT via virtualbox.
**enp0s8** has ip 172.17.8.101 and is setup for host only

On the second VM (core-02) enp0s3 has the same IP and enp0s8 has ip 172.17.8.102.

The interface **docker0** on both has the IP 10.1.42.1. When I launch my containers and list the network interfaces they can see, it only shows the loopback interface. If I launch with `--net host` I see all the host interfaces.

Is there a way to launch containers without `--net host` but still have traffic routed via the enp0s8 interface?

How do I know which interface docker will select to "bind" ports to or to send traffic on?

If I run a container that emits multicast packets with `--net host` the host computer (not in VM) can see them but the other vm cannot (if also run with `--net host`.

Containers on the same host can see the multicast packets even if run without `--net host`.

Is there something I can change in the vagrant setup to make docker use the private host-only network for containers or will it automatically use every network?

Is this possibly a routing rules issues?

Thanks for any guidance in advance on this obscure topic. If there is a better way to ask it or other place I can try that. I wanted to start here since this seems network setup related and I don't fully understand how docker plays with the network stack on the container host yet.

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1368
