### ISSUE TITLE
CoreOS constantly prints kernel mesaage of docker container.

### ISSUE THREAD

**Issue by liangsuilong** [coreos/coreos-vagrant#158]
![coreos_print](https://cloud.githubusercontent.com/assets/152888/4042637/35e2d9cc-2d06-11e4-8211-94170b231436.png)

Some docker containers are set to boot automatically by me via systemd. When I boot CoreOS, tty console is constantly printing kernel message of docker containers.  It is quite annoyed at me. I cannot  get login dialog, and cannot get ethernet IP address and MAC address. If there is something wrong for docker container so that container  automatically reboots via systemd, the kernel message on the screen will never stop. 

Could I disable kernel output on the tty0 screen? It is quite import for me. Is there any settings in CoreOS?

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1367
