### ISSUE TITLE
access denied by server while mounting

### ISSUE THREAD

**Issue by Integralist** [coreos/coreos-vagrant#159]
I'm using the following (slightly modified) version of your Vagrantfile with VMWare Version 6.0.4 (1887983)...

```ruby
$update_channel = "alpha"

Vagrant.configure("2") do |config|

  config.vm.box = "coreos-%s" % $update_channel
  config.vm.box_version = ">= 308.0.1"

  # Box URL (overridden for VMware)
  config.vm.box_url = "http://%s.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json" % $update_channel
  config.vm.provider :vmware_fusion do |vb, override|
    override.vm.box_url = "http://%s.release.core-os.net/amd64-usr/current/coreos_production_vagrant_vmware_fusion.json" % $update_channel
  end

  # VirtualBox doesn't have guest additions (or a functional vboxsf) in CoreOS
  # So here we're helping Vagrant to be smarter with its configuration
  config.vm.provider :virtualbox do |v|
    v.check_guest_additions = false
    v.functional_vboxsf     = false
  end

  # Resolve issue with a specific Vagrant plugin by preventing it from updating
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

  # Sets a hostname for the VM
  config.vm.hostname = "coreos-%s" % $update_channel

  # Configure the VM's Memory and CPU allocation
  config.vm.provider :virtualbox do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  # 172 is a private network range (we add this in ~/.zshrc like so: `export DOCKER_HOST=tcp://172.17.8.100:2375`)
  config.vm.network :private_network, ip: "172.17.8.100"

  # Enable NFS for sharing the host machine into the coreos-vagrant VM
  config.vm.synced_folder ".", "/home/core/share",
                          id: "core",
                          :nfs => true,
                          :mount_options => ['nolock,vers=3,udp']

  config.vm.provision "shell" do |s|
    s.privileged = true
    s.path = "provision.sh"
  end

end
```

But when I run `vagrant up --provider=vmware_fusion` I get the following error...

```
Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Cloning VMware VM: 'coreos-alpha'. This can take some time...
==> default: Checking if box 'coreos-alpha' is up to date...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Starting the VMware VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 172.16.82.134:22
    default: SSH username: core
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Forwarding ports...
    default: -- 22 => 2200
==> default: Setting hostname...
==> default: Configuring network adapters within the VM...
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
==> default: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'nolock,vers=3,udp' 172.17.8.1:'/Users/markmcdonnell/Box Sync/Library/Docker' /home/core/share

Stdout from the command:



Stderr from the command:

mount.nfs: access denied by server while mounting 172.17.8.1:/Users/markmcdonnell/Box Sync/Library/Docker
```

**Comment by crobays** [comment]
Never thought this would be the problem but i fixed it by setting my `/etc/hosts` to the default.
Hope somebody else is helped by this

**Comment by derek-adair** [comment]
Also having this problem...

Vagrant 1.7.2
Virtualbox 4.3.10
Ubuntu 14.04 (both host/guest)

**Comment by adopudi** [comment]
Windows 7
Vagrant 1.7.2
vagrant-winnfsd (1.0.11)

The only way I have seen synced_folders consistently work in Win 7 is by mounting the whole windows user home directory:

`config.vm.synced_folder ENV['HOME'], "/home/core/share", id: "home", :nfs => true, :mount_options => ['nolock,vers=3,udp']`

**Comment by janschultecom** [comment]
Had the same problem. I think the problem might be that the IP range is already in use in the network, so that coreos cannot assign it again. When changing from "172.17.8.#{i+100}" to "172.17.9.#{i+100}" and clearing /etc/export it worked again. In my case, a colleague was also using vagrant at the same time.

**Comment by derek-adair** [comment]
I also got NFS working by doing a similar thing as @janschultecom.  Clearing /etc/exports, trying various private ips.

**Comment by cameron** [comment]
Samesies

OS X 10.10.1
Vagrant 1.6.5 & 1.7.2
coreos-beta 612.1.0.

`vagrant reload` set everything straight.

**Comment by majidaldo** [comment]
windows 8.1. `vagrant halt` then `up` fixed it.

**Comment by IbnSaeed** [comment]
Having the same problem with vagrant using winnfsd on windows 8.1 pro

**Comment by majidaldo** [comment]
make sure no other boxes are using the specified network. in virtualbox file>prefs>net>hostonly, make changes.

heck i just deleted all the networks and started fresh.

**Comment by mcloide** [comment]
I had the same issue but it isn't related to IP.

This is the error from vagrant:

```
mount -o 'nolock,vers=3,udp' 33.33.33.20:'/Users/myuser/vm-htdocs/my-repo' /var/www

Stdout from the command:



Stderr from the command:

mount.nfs: access denied by server while mounting 33.33.33.20:/Users/myuser/vm-htdocs/my-repo
```

I do happen to have 2 other Vagrant vms running and sharing ```/Users/myuser/vm-htdocs``` and my ```/etc/exports``` does have these 2 entries there.

Whenever I try to mount ```/Users/myuser/vm-htdocs/my-repo``` on a 3rd vagrant box, it fails.

From all the tests done the way to fix was to comment the mounted entry under ```/etc/exports``` for the other 2 vagrant boxes and after that the ```/Users/myuser/vm-htdocs/my-repo``` mounts with no problem.

Solutions:

- Have one directory per project and make it the parent of self
- Have only one parent directory mounted and then change your httpd conf file to point to the correct location

By all means I'm only mounting

```
/Users/myuser/my-repo => /vagrant_data
```

Hope this helps everyone else having the same issue.

Note:

```
O.S.: OSX
VirtuaBox: 4.3.26
Vagrant: 1.7

Most of the configuration file from vagrant was built using PuPHPet.com

**Comment by ebuildy** [comment]
Vagrant should check and validate the NFS exports before then prompt a clear message if issue, lot of devs come across this, there are a ton of stackoverflow posts related to this "bug".

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1366
