### ISSUE TITLE
error: You specified a box version constraint with a direct box file path

### ISSUE THREAD

**Issue by hustcat** [coreos/coreos-vagrant#165]
$ vagrant up
Bringing machine 'core-01' up with 'virtualbox' provider...
Bringing machine 'core-02' up with 'virtualbox' provider...
Bringing machine 'core-03' up with 'virtualbox' provider...
==> core-01: Box 'coreos-beta' could not be found. Attempting to find and install...
    core-01: Box Provider: virtualbox
    core-01: Box Version: >= 308.0.1
You specified a box version constraint with a direct box file
path. Box version constraints only work with boxes from Vagrant
Cloud or a custom box host. Please remove the version constraint
and try again.

what's wrong?

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1365
