### ISSUE TITLE
fleetctl list-machines  failed

### ISSUE THREAD

**Issue by hustcat** [coreos/coreos-vagrant#167]
$ vagrant up --provision
Bringing machine 'core-01' up with 'virtualbox' provider...
Bringing machine 'core-02' up with 'virtualbox' provider...
Bringing machine 'core-03' up with 'virtualbox' provider...
==> core-01: Importing base box 'coreos-beta'...
==> core-01: Matching MAC address for NAT networking...
==> core-01: Checking if box 'coreos-beta' is up to date...
==> core-01: Setting the name of the VM: coreos-vagrant_core-01_1409893206332_38217
==> core-01: Fixed port collision for 22 => 2222. Now on port 2200.
==> core-01: Clearing any previously set network interfaces...
==> core-01: Preparing network interfaces based on configuration...
    core-01: Adapter 1: nat
    core-01: Adapter 2: hostonly
==> core-01: Forwarding ports...
    core-01: 22 => 2200 (adapter 1)
==> core-01: Running 'pre-boot' VM customizations...
==> core-01: Booting VM...
==> core-01: Waiting for machine to boot. This may take a few minutes...
    core-01: SSH address: 127.0.0.1:2200
    core-01: SSH username: core
    core-01: SSH auth method: private key
    core-01: Warning: Connection timeout. Retrying...
==> core-01: Machine booted and ready!
==> core-01: Setting hostname...
==> core-01: Configuring and enabling network interfaces...
==> core-01: Running provisioner: file...
==> core-01: Running provisioner: shell...
    core-01: Running: inline script
==> core-02: Importing base box 'coreos-beta'...
==> core-02: Matching MAC address for NAT networking...
==> core-02: Checking if box 'coreos-beta' is up to date...
==> core-02: Setting the name of the VM: coreos-vagrant_core-02_1409893227395_74925
==> core-02: Fixed port collision for 22 => 2222. Now on port 2201.
==> core-02: Clearing any previously set network interfaces...
==> core-02: Preparing network interfaces based on configuration...
    core-02: Adapter 1: nat
    core-02: Adapter 2: hostonly
==> core-02: Forwarding ports...
    core-02: 22 => 2201 (adapter 1)
==> core-02: Running 'pre-boot' VM customizations...
==> core-02: Booting VM...
==> core-02: Waiting for machine to boot. This may take a few minutes...
    core-02: SSH address: 127.0.0.1:2201
    core-02: SSH username: core
    core-02: SSH auth method: private key
    core-02: Warning: Connection timeout. Retrying...
==> core-02: Machine booted and ready!
==> core-02: Setting hostname...
==> core-02: Configuring and enabling network interfaces...
==> core-02: Running provisioner: file...
==> core-02: Running provisioner: shell...
    core-02: Running: inline script
==> core-03: Importing base box 'coreos-beta'...
==> core-03: Matching MAC address for NAT networking...
==> core-03: Checking if box 'coreos-beta' is up to date...
==> core-03: Setting the name of the VM: coreos-vagrant_core-03_1409893250410_14165
==> core-03: Fixed port collision for 22 => 2222. Now on port 2202.
==> core-03: Clearing any previously set network interfaces...
==> core-03: Preparing network interfaces based on configuration...
    core-03: Adapter 1: nat
    core-03: Adapter 2: hostonly
==> core-03: Forwarding ports...
    core-03: 22 => 2202 (adapter 1)
==> core-03: Running 'pre-boot' VM customizations...
==> core-03: Booting VM...
==> core-03: Waiting for machine to boot. This may take a few minutes...
    core-03: SSH address: 127.0.0.1:2202
    core-03: SSH username: core
    core-03: SSH auth method: private key
    core-03: Warning: Connection timeout. Retrying...
==> core-03: Machine booted and ready!
==> core-03: Setting hostname...
==> core-03: Configuring and enabling network interfaces...
==> core-03: Running provisioner: file...
==> core-03: Running provisioner: shell...
    core-03: Running: inline script
yinyedeMacBook-Pro:coreos-vagrant yy$ vagrant status
Current machine states:

core-01                   running (virtualbox)
core-02                   running (virtualbox)
core-03                   running (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
yinyedeMacBook-Pro:coreos-vagrant yy$ fleetctl list-machines
INFO client.go:278: Failed getting response from http://127.0.0.1:4001/: dial tcp 127.0.0.1:4001: connection refused
ERROR client.go:200: Unable to get result for {Get /_coreos.com/fleet/machines}, retrying in 100ms

$cat config.rb
$num_instances=3
$update_channel='beta'

$ cat user-data
#cloud-config

coreos:
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    # WARNING: replace each time you 'vagrant destroy'
    discovery: https://discovery.etcd.io/4659e1b89324505b75aa14189fe2ba3f
    addr: $public_ipv4:4001
    peer-addr: $public_ipv4:7001
  fleet:
    public-ip: $public_ipv4
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: docker-tcp.socket
      command: start
      enable: true
      content: |
        [Unit]
        Description=Docker Socket for the API

        [Socket]
        ListenStream=2375
        Service=docker.service
        BindIPv6Only=both

        [Install]
        WantedBy=sockets.target

**Comment by iamthemuffinman** [comment]
I'm having the same problem. I've tried this on bare-metal and in Vagrant and I get the same result each time I try. Etcd will attempt to start and then crap out on connecting. Here's the log. https://gist.github.com/65704c085394606c19e9.git

**Comment by mattma** [comment]
I have the exact same problem like @rhacker . How did you fix it?

```bash
core@core-01 /run/systemd/system $ journalctl -u etcd
-- Logs begin at Sun 2015-03-29 07:19:55 UTC, end at Sun 2015-03-29 07:32:59 UTC. --
Mar 29 07:20:06 core-01 systemd[1]: Starting etcd...
Mar 29 07:20:06 core-01 systemd[1]: Started etcd.
Mar 29 07:20:06 core-01 etcd[907]: [etcd] Mar 29 07:20:06.131 INFO      | Discovery via https://discovery.etcd.io using prefix /1737989f577db8b
Mar 29 07:20:08 core-01 etcd[907]: [etcd] Mar 29 07:20:08.474 INFO      | Discovery _state was empty, so this machine is the initial leader.
Mar 29 07:20:08 core-01 etcd[907]: [etcd] Mar 29 07:20:08.475 INFO      | Discovery fetched back peer list: []
Mar 29 07:20:08 core-01 etcd[907]: [etcd] Mar 29 07:20:08.475 INFO      | coreos0 is starting a new cluster
Mar 29 07:20:08 core-01 etcd[907]: [etcd] Mar 29 07:20:08.478 INFO      | etcd server [name coreos0, listen on :4001, advertised url http://172
Mar 29 07:20:08 core-01 etcd[907]: [etcd] Mar 29 07:20:08.479 INFO      | peer server [name coreos0, listen on :7001, advertised url http://172
Mar 29 07:20:08 core-01 etcd[907]: [etcd] Mar 29 07:20:08.479 INFO      | coreos0 starting in peer mode
Mar 29 07:20:08 core-01 etcd[907]: [etcd] Mar 29 07:20:08.479 INFO      | coreos0: state changed from 'initialized' to 'follower'.
Mar 29 07:20:08 core-01 etcd[907]: [etcd] Mar 29 07:20:08.479 INFO      | coreos0: state changed from 'follower' to 'leader'.
Mar 29 07:20:08 core-01 etcd[907]: [etcd] Mar 29 07:20:08.479 INFO      | coreos0: leader changed from '' to 'coreos0'.
Mar 29 07:20:08 core-01 etcd[907]: [etcd] Mar 29 07:20:08.505 INFO      | coreos0: available_internal_versions [1] is registered into key space
```

The discovery token is freshly generated, and vagrant was in `not created` state. Run `vagrant up`. All three machines is running just fine. 

```bash
export FLEETCTL_FUNNEL=172.17.8.101
ssh-add
```

and make sure that i have successfully add my private key because that I can do `ssh -A core@172.17.8.101` to get into the shell. 

Stuck here for a few hours... :(

**Comment by dgeske** [comment]
@jonboulle Thanks! :+1:

**Comment by mattma** [comment]
fixed my issue by remove the `insecure_private_key`, and rerun `vagrant up`. it is all good.

**Comment by ruudk** [comment]
For anyone having the same problem: for me it was due the fact that I didn't rename `user-data.sample` to `user-data`. Once I did that, I `vagrant destroy`-ed my images, and ran `vagrant up` again. Then it worked :)

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1364
