### ISSUE TITLE
Create Parallels Vagrant Box

### ISSUE THREAD

**Issue by KellyLSB** [coreos/coreos-vagrant#173]
If you would; please create a Parallels Vagrant Box.

**Comment by AntonioMeireles** [comment]
fwiw i 've made available  **up to date** CoreOS parallels boxes at https://atlas.hashicorp.com/AntonioMeireles/boxes/. i'll try to keep them up to date, and as close to pristine upstream ones as possible, too :smile:  . 

to invoke them ... 
```
 config.vm.provider "parallels" do |v, override|
       override.vm.box = "AntonioMeireles/coreos-%s" % $update_channel
       override.vm.box_url = "https://vagrantcloud.com/AntonioMeireles/coreos-%s" % $update_channel
    end
 end
```
if you hadn't installed it before ... 
```
vagrant plugin install vagrant-parallels  
```
Then run once to init the box:
```
vagrant up --provider parallels
```
Afterwards the usual ```vagrant up``` will work just fine.

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1361
