### ISSUE TITLE
Understanding how cloud-config gets loaded and used

### ISSUE THREAD

**Issue by lgomez** [coreos/coreos-vagrant#180]
Hi,

This is not an issue per se but more of a request for confirmation that I am understanding this correctly.

I was struggling to understand what was happening [Vagrantfile#L95-L96](/coreos/coreos-vagrant/blob/master/Vagrantfile#L95-L96) and why the image used by Vagrant had the vagrant-specific directory: /var/lib/coreos-vagrant/ and file: /var/lib/coreos-vagrant/vagrantfile-user-data. I got here because I'm trying to wrap my head around CoreOS, Fleet, etcd, etc. I want to use these for as much of my web/service development as I can. I hope to be able to emulate production clusters locally and hopefully be able to use the same cloud-config or a very similar one in localdev and production. With that in mind, I need to understand what goes where and why.

So I went into a CoreOS instance via `vagrant ssh` and, after much Googling that got me to realize systemctl was what I needed to understand, ran `systemctl list-units | grep vagrant` which yielded:
```
coreos-cloudinit-vagrant-user.path                                                       loaded active running   coreos-cloudinit-vagrant-user.path
user-cloudinit@var-lib-coreos\x2dvagrant-vagrantfile\x2duser\x2ddata.service             loaded active exited    Load cloud-config from /var/lib/coreos-vagrant/vagrantfile-user-data
```
This tells me there are at least two units related specifically to vagrant. One seems to set up a path and the other loads a cloud-config file from a file within said path (as stated in the description).

I then ran `systemctl show coreos-cloudinit-vagrant-user.path` and got (truncated for brevity):
```
PathExists=/var/lib/coreos-vagrant/vagrantfile-user-data
MakeDirectory=no
Before=user-cloudinit@var-lib-coreos\x2dvagrant-vagrantfile\x2duser\x2ddata.service paths.target shutdown.target
```
This seems to ensure that:

1. `/var/lib/coreos-vagrant/vagrantfile-user-data` exists and...
2. this unit is loaded *Before* `user-cloudinit@var-lib-coreos\x2dvagrant-vagrantfile\x2duser\x2ddata.service` but it...
3. *does not* create the directory if it doesn't exist by setting `MakeDirectory=no`

Correct?

Then I ran `systemctl show user-cloudinit@var-lib-coreos\x2dvagrant-vagrantfile\x2duser\x2ddata.service` which yielded a number of lines but most importantly:
```
ExecStart={ path=/usr/bin/coreos-cloudinit ; argv[]=/usr/bin/coreos-cloudinit --from-file=%f ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
```
In there I see `/usr/bin/coreos-cloudinit` being called with the `%f` specifier which refers to the instance name (I believe). This is how the user-data file gets consumed, correct?

I tend to prefer keeping things simple, customizing or depending on as little as possible. I would like to know why the decision to create a Vagrant-specific directory and file and not simply place the cloud-config in a predetermined location since CoreOS comes with Fleet built in and should expect it to exist somewhere already, no?

Understanding this will help me figure out if I can share configuration files between Vagrant (localdev) and production (probably GCE) and probably how. I don't know if that'll be possible but it's worth a try.

Thank you,

Luis

**Comment by nr17** [comment]
Hi Luis,

I have a similar requirement as yours, i.e. emulating production env using VMs, but keeping the configuration and corresponding directories as close to the actual production env.

-Nitin

**Comment by starkovv** [comment]
@nr17 +1

**Comment by lgomez** [comment]
@nr17 & @starkovv My work on this was interrupted by other issues and projects but I haven't given up on it yet. I'll post a followup here as soon as I can. Sorry for not being able to get back sooner.

**Comment by mattma** [comment]
I have a similar question about `/var/lib/coreos-vagrant/vagrantfile-user-data`.

I have seen several units defined in `vagrantfile-user-data`, for example,

```bash
coreos:
  etcd2:
    name: master
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    advertise-client-urls: http://$public_ipv4:2379,http://$public_ipv4:4001
    listen-peer-urls: http://$private_ipv4:2380,http://$private_ipv4:7001
  fleet:
    public-ip: $public_ipv4
    metadata: "role=master"
  flannel:
    interface: eth1
 ...
```

Those services have been started automatically when vagrant machine is up. I do not see the `fleetctl start *.service` or anything along this line to start those service 

```bash
      if File.exist?(CLOUD_CONFIG_PATH)
        config.vm.provision :file, :source => "#{CLOUD_CONFIG_PATH}", :destination => "/tmp/vagrantfile-user-data"
        config.vm.provision :shell, :inline => "mv /tmp/vagrantfile-user-data /var/lib/coreos-vagrant/", :privileged => true
      end
```

Does `CoreOS` start this `cloud-config` file (vagrantfile-user-data ) by default? If I want my production server to load the same exactly `cloud-config` file, what name and path should I use to auto load those default services?

thanks
