### ISSUE TITLE
vagrant up causes `no space left on device`

### ISSUE THREAD

**Issue by sjackman** [coreos/coreos-vagrant#181]
See also docker/docker#8804. I'm not sure whether this is primarily a Docker issue, a Vagrant issue, or a Vagrant CoreOS issue. Please reassign this issue as necessary.

Running `vagrant up` on coreos-vagrant causes the error `scp: /var/tmp/hostname.yml: No space left on device (RuntimeError)`. See below for details. The volumes do not appear full.

```
sh-4.2# df
Filesystem     1K-blocks     Used Available Use% Mounted on
rootfs          16793600 12362164   3910668  76% /
devtmpfs         2014476        0   2014476   0% /dev
tmpfs            2026352        0   2026352   0% /dev/shm
tmpfs            2026352      236   2026116   1% /run
tmpfs            2026352        0   2026352   0% /sys/fs/cgroup
/dev/sda9       16793600 12362164   3910668  76% /
/dev/sda3        1032088   294556    685104  31% /usr
tmpfs            2026352        0   2026352   0% /media
tmpfs            2026352        0   2026352   0% /tmp
/dev/sda6         110576       88    101316   1% /usr/share/oem
/dev/sda9       16793600 12362164   3910668  76% /var/lib/docker/btrfs
```

**Comment by waisbrot** [comment]
I'm seeing exactly this with CoreOS alpha (633.1.0) on Vagrant using the VMWare provider. Did you ever find a solution?

**Comment by sjackman** [comment]
No, I didn't. I blew away the machine and started over.

**Comment by palerdot** [comment]
I came across the same problem. When I inspected the disk usage I saw that **mongo** was filling up the disk. I deleted mongo files and uninstalled it since I didn't need mongo. This fixed the issue in my machine.

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1359
