### ISSUE TITLE
There was a problem while downloading the metadata for your box

### ISSUE THREAD

**Issue by jnuc093** [coreos/coreos-vagrant#191]
$ vagrant up
Bringing machine 'core-01' up with 'virtualbox' provider...
==> core-01: Checking if box 'coreos-beta' is up to date...
==> core-01: There was a problem while downloading the metadata for your box
==> core-01: to check for updates. This is not an error, since it is usually due
==> core-01: to temporary network problems. This is just a warning. The problem
==> core-01: encountered was:
==> core-01:
==> core-01: Failed connect to beta.release.core-os.net:80; No error
==> core-01:
==> core-01: If you want to check for box updates, verify your network connection
==> core-01: is valid and try again.
==> core-01: VirtualBox VM is already running.

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1355
