### ISSUE TITLE
Failed connect to stable.release.core-os.net:443; No error

### ISSUE THREAD

**Issue by gindasoo** [coreos/coreos-vagrant#194]
D:\coreos-vagrant>vagrant up
Bringing machine 'core-01' up with 'virtualbox' provider...
==> core-01: Box 'coreos-stable' could not be found. Attempting to find and inst
all...
core-01: Box Provider: virtualbox
core-01: Box Version: >= 0
==> core-01: Adding box 'coreos-stable' (v0) for provider: virtualbox
core-01: Downloading: https://stable.release.core-os.net/amd64-usr/current/c
oreos_production_vagrant.json
core-01: Progress: 0% (Rate: 0curl:/s, Estimated time remaining: --:--:--)
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Failed connect to stable.release.core-os.net:443; No error

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1353
