### ISSUE TITLE
Port forwarding: how to forward a port of coreOS to a port of my local machine

### ISSUE THREAD

**Issue by Ke-Dou** [coreos/coreos-vagrant#195]
Hi,

I have a cluster of 4 coreOS VMs running on my local machine, and I am running a web application with Docker on one of them.

I forwarded the port 80 my application runs on to  the port 8080 of coreOS VM.

My problem is: how can I make another hop from my local machine to the CoreOS port, so that I can reach my application on my local machine? 

I have tried to do this with VBoxManage of Virtualbox (the method is described here: http://www.linuxjournal.com/content/tech-tip-port-forwarding-virtualbox-vboxmanage), but it's not working. 

I also tried the Vagrant forwarded ports method (https://docs.vagrantup.com/v2/networking/forwarded_ports.html), and put the following script in the 
Vagrantfile:

Vagrant.configure("2") do |config|
  config.vm.network "forwarded_port", guest: 80, host: 8888, auto_correct: true
end

This will forward the port 80 of core-01 to the port 8888 of local host, and forward the port 80 of other cores to some random ports of local host like 2201, 2203, etc. The problem here is we are not sure through which port of local host to access the web service, unless we try every of the ports including 8888 and the other random ports.

Any ideas will be appreciated. 

Thanks in advance,
Ke

**Comment by kastork** [comment]
Same problem here, even with just a single core-os vm.  Any success figuring it out?

**Comment by pikeas** [comment]
You can set `config.vm.network` per host in the cluster.

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1352
