### ISSUE TITLE
VBoxManage.exe: error: Failed to create the host-only adapter

### ISSUE THREAD

**Issue by bodote** [coreos/coreos-vagrant#197]
using VirtualBox 4.3.0 r89960

vagrant up : 

Bringing machine 'core-01' up with 'virtualbox' provider...
==> core-01: Checking if box 'coreos-alpha' is up to date...
==> core-01: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: E_INVALIDARG
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Assertion failed: [!aGuid.isValid()] at 'D:\tinderbox\win
-4.3\src\VBox\Main\src-server\HostNetworkInterfaceImpl.cpp' (74) in long __cdecl
 HostNetworkInterface::init(class com::Bstr,class com::Bstr,class com::Guid,enum
 __MIDL___MIDL_itf_VirtualBox_0000_0000_0034).
VBoxManage.exe: error: Please contact the product vendor!
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component HostNetworkI
nterface, interface IHostNetworkInterface
VBoxManage.exe: error: Context: "int __cdecl handleCreate(struct HandlerArg *,in
t,int *)" at line 66 of file VBoxManageHostonly.cpp

**Comment by bodote** [comment]
after VirtualBox update to 4.3.20 the problem disapeared

**Comment by JMonsorno** [comment]
Having same issue on VB 5.0.16 r105871 Vagrant 1.8.1

**Comment by hannes011** [comment]
ich auch

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1350
