### ISSUE TITLE
Win 7 vagrant up failed: Connection timeout

### ISSUE THREAD

**Issue by xuxiong** [coreos/coreos-vagrant#201]
* Win7
* VirtualBox 4.3.20
* vagrant 1.7.2
* box from http://stable.release.core-os.net/amd64-usr/522.4.0/coreos_production_vagrant.box

D:\coreos-vagrant>vagrant up
Bringing machine 'core-01' up with 'virtualbox' provider...
==> core-01: Clearing any previously set forwarded ports...
==> core-01: Clearing any previously set network interfaces...
==> core-01: Preparing network interfaces based on configuration...
    core-01: Adapter 1: nat
    core-01: Adapter 2: hostonly
==> core-01: Forwarding ports...
    core-01: 22 => 2222 (adapter 1)
==> core-01: Running 'pre-boot' VM customizations...
==> core-01: Booting VM...
==> core-01: Waiting for machine to boot. This may take a few minutes...
    core-01: SSH address: 127.0.0.1:2222
    core-01: SSH username: core
    core-01: SSH auth method: private key
    core-01: Warning: Connection timeout. Retrying...
    core-01: Warning: Connection timeout. Retrying...
    core-01: Warning: Connection timeout. Retrying...
...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

**Comment by bcwaldon** [comment]
Does the VM ever boot? Have you tried raising the boot_timeout?

**Comment by xuxiong** [comment]
I can see VM running in VirtualBox manager.
I changed the boot_timeout:
```
$ git diff
diff --git a/Vagrantfile b/Vagrantfile
index 3c881ec..435fc72 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -10,7 +10,7 @@ CONFIG = File.join(File.dirname(__FILE__), "config.rb")

 # Defaults for config options defined in CONFIG
 $num_instances = 1
-$update_channel = "alpha"
+$update_channel = "stable"
 $enable_serial_logging = false
 $vb_gui = false
 $vb_memory = 1024
@@ -27,11 +27,12 @@ if File.exist?(CONFIG)
 end

 Vagrant.configure("2") do |config|
+  config.vm.boot_timeout = 300
   # always use Vagrants insecure key
   config.ssh.insert_key = false

   config.vm.box = "coreos-%s" % $update_channel
-  config.vm.box_version = ">= 308.0.1"
+  #config.vm.box_version = ">= 308.0.1"
   config.vm.box_url = "http://%s.release.core-os.net/amd64-usr/current/coreos_p

   config.vm.provider :vmware_fusion do |vb, override|
```

Please see the vagrant log here: https://gist.github.com/xuxiong/f5b29e5004a263543132#file-vagrant-log

```
$ vagrant up --debug 2>&1 | tee vagrant.log
```

**Comment by bcwaldon** [comment]
Ok, there's clearly something wrong. You're running on the same versions of vagrant and virtualbox, so no easy fix there. I don't have any experience with Vagrant on Windows 7, so I'm not really sure what to suggest.

**Comment by xuxiong** [comment]
Can CoreOS run on Win7 without Vagrant?

**Comment by xuxiong** [comment]
I finally solved this problem by enabling the visualization setting in bios setting.
