### ISSUE TITLE
Issue - starting a coreos vagrant cluster inside a VM.

### ISSUE THREAD

**Issue by alok87** [coreos/coreos-vagrant#202]
Hi,

I have a windows 7 laptop. I have installed a centos machine inside virtual box in my latop.
Inside Centos Virtual machine, i installed Vagrant, git and virtual box and tried to bring the coreos vagrant up. It is not coming up and throwing the below error. I have increasing the timeout but to no success.

==> core-01: Waiting for machine to boot. This may take a few minutes...
core-01: SSH address: 127.0.0.1:2222
core-01: SSH username: core
core-01: SSH auth method: private key
core-01: Warning: Connection timeout. Retrying...

Please suggest. What could be the issue in starting coreos vagrant cluster inside a VM?

**Comment by Lawouach** [comment]
The problem is that VT-x support is expected from the CoreOS vagrant box and you cannot have vtx enabled for VM-within-VM in VirtualBox. This is likely the reason why it hangs. The VM never boots up.

See https://www.virtualbox.org/ticket/4032

**Comment by Keepintouchh** [comment]
Hello i have the same problem for 3 month now i Beg for help pleas

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1349
