### ISSUE TITLE
Add "Remember me" checkbox

### ISSUE THREAD

**Issue by saientzg** [coreos/coreos-vagrant#203]
Add optional username and/or password persistency for login.

**Comment by bcwaldon** [comment]
@saientzg I see that you've closed this issue, but could you share any more info on your original thinking?

**Comment by saientzg** [comment]
I'm sorry. I created this issue by mistake (wrong project) so I closed it immediately. Someone with enough permissions should probably delete it.

**Comment by bcwaldon** [comment]
@saientzg no worries
