### ISSUE TITLE
"E437: terminal capability "cm" required" error message, when I try to use VIM

### ISSUE THREAD

**Issue by DJviolin** [coreos/coreos-vagrant#206]
I've got this error message every time when I try to use VIM:
"E437: terminal capability "cm" required"

This is a new Vagrant Coreos installation.

**Comment by bcwaldon** [comment]
What host OS are you running?

**Comment by DJviolin** [comment]
I use Win7x64. The issue is solved (for me) by using VIM with XTERM command:

https://groups.google.com/forum/#!topic/coreos-dev/LUSPSYsv-Ew

**Comment by bcwaldon** [comment]
Ok - I don't have any experience with windows, so I can't really help you debug this any further. Since you found a solution, I'm going to close this.
