### ISSUE TITLE
 Failed to get COMM, falling back to the command line.

### ISSUE THREAD

**Issue by IbnSaeed** [coreos/coreos-vagrant#210]
Hello

I am running Coreos beta VERSION=584.0.0

I get the following error when i use a drush command inside a running docker container.

[ 1893.297925] docker0: port 4(veth9ad9f9f) entered disabled state
[ 1893.299041] device veth9ad9f9f left promiscuous mode
[ 1893.300611] docker0: port 4(veth9ad9f9f) entered disabled state
[ 1897.245112] device veth13e3506 entered promiscuous mode
[ 1897.250081] IPv6: ADDRCONF(NETDEV_UP): veth13e3506: link is not ready
[ 1897.414930] eth0: renamed from veth4ff9c63
[ 1897.432637] IPv6: ADDRCONF(NETDEV_CHANGE): veth13e3506: link becomes ready
[ 1897.433879] docker0: port 4(veth13e3506) entered forwarding state
[ 1897.434856] docker0: port 4(veth13e3506) entered forwarding state
[ 1912.481114] docker0: port 4(veth13e3506) entered forwarding state
[ 2213.992984] systemd-coredump[2517]: Failed to get COMM, falling back to the command line.
[ 2213.994054] systemd-coredump[2517]: Failed to get EXE.
[ 2221.378935] systemd-coredump[2530]: Failed to get COMM, falling back to the command line.
[ 2221.380601] systemd-coredump[2530]: Failed to get EXE.
[ 2280.044996] systemd-coredump[2601]: Failed to get COMM, falling back to the command line.
[ 2280.047807] systemd-coredump[2601]: Failed to get EXE.
[ 2497.068099] systemd-coredump[2691]: Failed to get COMM, falling back to the command line.
[ 2497.099913] systemd-coredump[2691]: Failed to get EXE.
[ 2600.703980] systemd-coredump[2724]: Failed to get COMM, falling back to the command line.
[ 2600.707333] systemd-coredump[2724]: Failed to get EXE.
[ 5169.413761] systemd-coredump[3141]: Failed to get COMM, falling back to the command line.
[ 5169.415308] systemd-coredump[3141]: Failed to get EXE.

**Comment by PhilipOrleans** [comment]
It happens to me too, kernel
uname -r
4.1.5-200.fc22.x86_64
rpm -qa | grep systemd
systemd-libs-219-21.fc22.i686
systemd-libs-219-21.fc22.x86_64
systemd-219-21.fc22.x86_64
systemd-python-219-21.fc22.x86_64
systemd-python3-219-21.fc22.x86_64
systemd-compat-libs-219-21.fc22.x86_64
rpm-plugin-systemd-inhibit-4.12.0.1-12.fc22.x86_64

I use LXC
 rpm -qa | grep lxc
lxc-1.1.2-2.fc22.x86_64
lxc-templates-1.1.2-2.fc22.x86_64
lxc-extra-1.1.2-2.fc22.x86_64
python3-lxc-1.1.2-2.fc22.x86_64
lxc-libs-1.1.2-2.fc22.x86_64

I have a virtual machine with FC 20
systemd-208-31.fc20.x86_64
systemd-libs-208-31.fc20.x86_64

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1346
