### ISSUE TITLE
Update etcd discovery token generation to work with etcd v2

### ISSUE THREAD

**Issue by bcwaldon** [coreos/coreos-vagrant#212]
The etcd discovery protocol has been tweaked with the v2 release, requiring that a given an expected cluster size. When using the public discovery service, this is as simple as making a request to `https://discovery.etcd.io/new?size=N` where `N` is the size of your cluster.

The code in `config.rb.sample` does not provide an explicit size, which results in a default of 3. This could cause unexpected behavior for people bringing up clusters larger or smaller than 3 nodes. When generating the new token, we simply need to take into account the `$num_instances` config variable and set the size query parameter accordingly.

**Comment by pikeas** [comment]
Seems reasonable, why is this a `wontfix`?

**Comment by bcwaldon** [comment]
Didn't mean to tag this as `wontfix`. Removing that label

**Comment by indiv0** [comment]
@bcwaldon Looked like this was closed by https://github.com/coreos/coreos-vagrant/pull/226.

**Comment by bcwaldon** [comment]
@indiv0 yep, good catch!
