### ISSUE TITLE
DNS resolution is not working on 607.0.0 in vagrant

### ISSUE THREAD

**Issue by msumme** [coreos/coreos-vagrant#215]
I had a box running 557.2.0, and ping works.
```
core@core-01 ~ $ ping google.com
PING google.com (216.58.216.206) 56(84) bytes of data.
64 bytes from 216.58.216.206: icmp_seq=1 ttl=55 time=19.4 ms
64 bytes from 216.58.216.206: icmp_seq=2 ttl=55 time=31.2 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 19.495/25.397/31.299/5.902 ms
```

When I upgrade to 607, I get "bad address: google.com" (or something to that effect).

I'm wondering if this is related to a glibc bug that affected busybox-static ping in gentoo?  

https://sourceware.org/bugzilla/show_bug.cgi?id=17250 

I have a feeling that may be relevant, since glibc 2.19 is in use in 607.0.0.  

One other thing I've noticed is that when I ping 10.0.2.3 in 607.0.0, I get timeouts, whereas in 557.2.0 it works consistently.

Any ideas how I can resolve this?  It's in the stable branch now.

**Comment by msumme** [comment]
10.0.2.3 is the IP address in /etc/resolv.conf in both cases - after reading this again, I realize I didn't make that clear.

Also - vagrant ssh doesn't seem to work with 607.0.0.

**Comment by crawford** [comment]
What errors are you getting with vagrant ssh?

**Comment by msumme** [comment]
no errors - just doesn't connect.  I also was unable to connect via port-forwarding from localhost ( 22 => 2222) 

But I was able to connect to the configured IP address ( 172.17.8.101 )

**Comment by crawford** [comment]
Hmm, `ssh core@localhost -p2222` worked fine for me. What version of vagrant is this?

**Comment by msumme** [comment]
Vagrant 1.7.2

**Comment by msumme** [comment]
That particular problem was not consistent - seemed very temperamental.
The issue with DNS resolution happened consistently.

**Comment by crawford** [comment]
I am using vagrant 1.6.3 with VirtualBox 4.3.20.

**Comment by msumme** [comment]
I have Vbox 4.3.22.  I tried upgrading and had the same issues.

**Comment by marineam** [comment]
Re the linked gentoo bug: We don't ship busybox, and ping is dynamically linked.

**Comment by crawford** [comment]
`ping google.com` works fine for me. Are you using the ping that comes with CoreOS? or is this within a container?

**Comment by msumme** [comment]
The ping is in CoreOS, not a container.

I'll run a quick test to see if it's a glibc problem.

**Comment by msumme** [comment]
The usual glibc workaround for this issue (export LD_LIBRARY_PATH=/lib) isn't helping.  So - it's probably not that.  

Any other ideas?  Things I can try to give more useful diagnostic info?

 I have a vagrant box running 557 + another running 607.  One is working fine - same configurations exactly.

**Comment by crawford** [comment]
Can you try spinning up a new 607 instance without any configuration?

**Comment by msumme** [comment]
I figured out part of the problem.

I have a registry server running locally - the other units pull from it (to get around needing an SSL cert on a remote repository) - using IAM credentials.  This also lets me easily control access for most of the team who doesn't need to work on the containers - so they just get readonly IAM creds.

The problem is that while docker pull (ExecStartPre for most of the units) is running against a non-resolvable name, the network seems to really slow down.  

This means that the registry docker image never loads - leaving the entire system broken.

This does not happen on 557, where the registry.service unit successfully pulls down the registry docker image, and then registers the hostname/ip to the /etc/hosts file, and the rest of the units all pull from the local-repository.com and start successfully.

You can see these 2 things running side-by-side.  Ping actually hangs until the one on the right resolves, and then outputs all at once.  You can see the really long ping times.

![image](https://cloud.githubusercontent.com/assets/462931/6700787/fb652f40-cce0-11e4-8ac4-6844c367a368.png)

I might be able to find a workaround for this on my local system, but why would trying to access a non-resolvable url cause so many problems?

**Comment by msumme** [comment]
It's a lot worse when 5 different units are all trying to pull their docker images at the non-resolvable url...

**Comment by msumme** [comment]
What would be the right way to describe this issue?  It's not an issue w/ DNS resolution exactly - just that the network access on the box slows to a crawl when trying to access a non-resolvable hostname.

**Comment by allenpc** [comment]
I can confirm that this still seems to happen with 647.2.0 and Vagrant 1.7.2

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1345
