### ISSUE TITLE
SSL_CONNECT error during vagrant up

### ISSUE THREAD

**Issue by sivaramsk** [coreos/coreos-vagrant#217]
I tried to bring up the latest coreos-vagrant and have this error. How do I make it work?

$ vagrant up
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: C:/Users/v673525/Documents/Code/TestCode/coreos-vagrant/Vagrantfile
Message: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1344
