### ISSUE TITLE
Is it possible to edit .bashrc or otherwise add an alias?

### ISSUE THREAD

**Issue by alberto56** [coreos/coreos-vagrant#221]
Hi,

in the vagrant box, we have ~/.bashrc as a symlink to /usr/share/skel/.bashrc, which contains

    ...
    # Put your fun stuff here.
    ...

I'd like to add an alias there, but I can't modify it:

    core@core-01 ~ $ echo "alias a=b" >> ~/.bashrc
    -bash: /home/core/.bashrc: Read-only file system
    core@core-01 ~ $ sudo echo "alias a=b" >> ~/.bashrc
    -bash: /home/core/.bashrc: Read-only file system
    core@core-01 ~ $ sudo su
    core-01 core # sudo echo "alias a=b" >> /home/core/.bashrc
    bash: /home/core/.bashrc: Read-only file system
    core-01 core # ls -lah /home/core | grep .bashrc
    lrwxrwxrwx  1 core core   28 Feb 14 05:27 .bashrc -> ../../usr/share/skel/.bashrc
    core-01 core # sudo echo "alias a=b" >> /usr/share/skel/.bashrc
    bash: /usr/share/skel/.bashrc: Read-only file system

Is there a prescribed way to modify .bashrc or otherwise add, say, a $PATH or alias? If so, how? Sub-question: what is "skel"?

Thanks!

**Comment by dpalomar** [comment]
Hello, you could dereference it :

    cp $(readlink .bashrc) .bashrc.new && mv .bashrc.new .bashrc

Now you  can write your _.bashrc_

**Comment by cgswong** [comment]
@alberto56 Use entries under `/etc/profile.d`, for example the below extract from my user_data  is what I use to setup my environment:
```
write_files:
- path: /etc/profile.d/aliases.sh
  content: |
    alias l='ls -lFh'
    alias ll='ls -lFhA'
```

**Comment by amadeusmozrt** [comment]
I tried several ways to add alias to the .bashrc in Vagrant.  This is what worked for me.

echo "alias alias1="some command"" >> .bashrc
the "\" in front of "some command" I took out make it work.

The best way I found how to add alias to the .bashrc in Vagrant was:
add the alias to both the .bashrc and .bashrc~ 
Then I restarted Vagrant with ~$ vagrant halt / ~$ vagrant up in a git bash window.

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1342
