### ISSUE TITLE
task blocked for more than 120 seconds

### ISSUE THREAD

**Issue by acasanova** [coreos/coreos-vagrant#222]
I'm using coreos-vagrant on a mac book pro.  The HHVM application I'm working on hangs after a certain user story is completed. When this happens docker becomes unresponsive. Running docker rm -f app to kill the container just hangs. I thought it was a segmentation fault but I can't find any core dumps in the usual locations in the container.

Checking docker stats app showed the memory usage was around 220MB and cpu was at about 1-3%. 

After running `journalctl | grep hhvm`, I am now curious what the following log means. Specifically the lines that state "blocked for more than 120 seconds". I'd love to get some more information if possible. Was this a kernel panic of sorts?

Apr 14 20:38:09 core-01 docker[760]: time="2015-04-14T20:38:09Z" level="info" msg="+job log(exec_start: bash , 2d8c91800890f5c11c2bc794e8d455449aeff8ef80fcb0efabd43ec35d720719, 192.168.254.96:5000/basehhvm:latest)"
Apr 14 20:38:09 core-01 docker[760]: time="2015-04-14T20:38:09Z" level="info" msg="-job log(exec_start: bash , 2d8c91800890f5c11c2bc794e8d455449aeff8ef80fcb0efabd43ec35d720719, 192.168.254.96:5000/basehhvm:latest) = OK (0)"
Apr 14 20:40:32 core-01 kernel: INFO: task hhvm:1577 blocked for more than 120 seconds.
Apr 14 20:40:32 core-01 kernel: hhvm            D ffff8800b5103ca8     0  1577   1371 0x00000000
Apr 14 20:40:32 core-01 kernel: INFO: task hhvm:1608 blocked for more than 120 seconds.
Apr 14 20:40:32 core-01 kernel: hhvm            D ffff8800b516bc58     0  1608   1371 0x00000000
Apr 14 20:42:32 core-01 kernel: INFO: task hhvm:1577 blocked for more than 120 seconds.
Apr 14 20:42:32 core-01 kernel: hhvm            D ffff8800b5103ca8     0  1577   1371 0x00000000
Apr 14 20:42:32 core-01 kernel: INFO: task hhvm:1608 blocked for more than 120 seconds.
Apr 14 20:42:32 core-01 kernel: hhvm            D ffff8800b516bc58     0  1608   1371 0x00000000
Apr 14 20:43:26 core-01 docker[760]: time="2015-04-14T20:43:26Z" level="info" msg="GET /v1.17/containers/leonardo_hhvm/stats"
Apr 14 20:43:26 core-01 docker[760]: time="2015-04-14T20:43:26Z" level="info" msg="+job container_stats(leonardo_hhvm)"
Apr 14 20:44:32 core-01 kernel: INFO: task hhvm:1545 blocked for more than 120 seconds.
Apr 14 20:44:32 core-01 kernel: hhvm            D ffff8800b4723c58     0  1545   1371 0x00000000
Apr 14 20:44:32 core-01 kernel: INFO: task hhvm:1577 blocked for more than 120 seconds.
Apr 14 20:44:32 core-01 kernel: hhvm            D ffff8800b5103ca8     0  1577   1371 0x00000000
Apr 14 20:44:32 core-01 kernel: INFO: task hhvm:1578 blocked for more than 120 seconds.
Apr 14 20:44:32 core-01 kernel: hhvm            D ffff8800b6453c58     0  1578   1371 0x00000000
Apr 14 20:44:32 core-01 kernel: INFO: task hhvm:1608 blocked for more than 120 seconds.
Apr 14 20:44:32 core-01 kernel: hhvm            D ffff8800b516bc58     0  1608   1371 0x00000000
Apr 14 20:46:32 core-01 kernel: INFO: task hhvm:1545 blocked for more than 120 seconds.
Apr 14 20:46:32 core-01 kernel: hhvm            D ffff8800b4723c58     0  1545   1371 0x00000000
Apr 14 20:46:32 core-01 kernel: INFO: task hhvm:1577 blocked for more than 120 seconds.
Apr 14 20:46:32 core-01 kernel: hhvm            D ffff8800b5103ca8     0  1577   1371 0x00000000 

Did some testing on other machines running docker. I could not reproduce the freezing and unresponsive behavior. 

I have alotted 3GB to the vm. The other boxes had 8GB and 16GB on centos6.6 and ubuntu 14.10 respectively. Giving the vm more ram had reproduced the issue sporadically.
Am I missing something.

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1341
