### ISSUE TITLE
client and server don't have same version

### ISSUE THREAD

**Issue by JoyceBabu** [coreos/coreos-vagrant#227]
I have installed launched a Virtualbox VM using vagrant running coreos. But when I try to connect to docker, I am getting the following error

FATA[0000] Error response from daemon: client and server don't have same version (client : 1.18, server: 1.17) 

Host is having Docker client 1.6 and CoreOS is running 1.5. I have tried alpha and stable channels and both installed 1.5. How can I upgrade docker to 1.6 in CoreOS?

**Comment by tslater** [comment]
I have the same issue.

**Comment by hiasinho** [comment]
Set `$update_channel='beta'` in `config.rb`. This uses CoreOS 681.0.0 with docker 1.6.2. See https://coreos.com/releases/

**Comment by windweller** [comment]
Now the problem simply becomes:

```
Error response from daemon: client and server don't have same version (client : 1.19, server: 1.18)
```

Still no fixes whatsoever. Changing it to `beta` won't help because now it's the latest version that CoreOS has not yet followed.

**Comment by ELLIOTTCABLE** [comment]
As I understand it, the go-to solution to this is to maintain multiple *local* instances of Docker.

(See: [DVM](https://github.com/getcarina/dvm), or possibly versions of Docker archived in the [homebrew-versions](https://github.com/Homebrew/homebrew-versions/blob/cdcb9f20/docker171.rb) tap.)

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1340
