### ISSUE TITLE
docker logs pipe shows empty file

### ISSUE THREAD

**Issue by dpalomar** [coreos/coreos-vagrant#232]
Hello, I don't know if this is an issue of coreos or docker in coreos. Others distros works fine.

Using `docker logs <container> >> file.log` shows log in stdout but the **file.log** is empty.

**Host:** _win8.1_
**Vagrant version:** _1.7.2_
**Docker Info:**

    Containers: 3
    Images: 9
    Storage Driver: overlay
    Backing Filesystem: extfs
    Execution Driver: native-0.2
    Kernel Version: 4.0.3
    Operating System: CoreOS 681.0.0
    CPUs: 1
    Total Memory: 997.9 MiB
    Name: core-01

**Docker version:**

    Client version: 1.6.2
    Client API version: 1.18
    Go version (client): go1.4.2
    Git commit (client): 7c8fca2-dirty
    OS/Arch (client): linux/amd64
    Server version: 1.6.2
    Server API version: 1.18
    Go version (server): go1.4.2
    Git commit (server): 7c8fca2-dirty
    OS/Arch (server): linux/amd64

**Comment by dpalomar** [comment]
Oops, it's my fault.
`docker logs` is **stderr**, so `2>file.log` works

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1339
