### ISSUE TITLE
Update documentation to mention NFS lack of support for mounting encrypted directories

### ISSUE THREAD

**Issue by publicus** [coreos/coreos-vagrant#238]
After quite a bit of trial and error yesterday trying to use the NFS mount feature in the coreos-vagrant Vagrantfile, I realized that `ecryptfs`-protected directories (which include home directories on many Ubuntu and Ubuntu-derivative systems) apparently aren't supported by NFS. I specifically noticed this with an `ecryptfs`-protected directory that was currently mounted, and that thus should presumably have been usable. This is an upstream NFS (and thus Vagrant) issue, but I think that it could be useful to mention in the coreos-vagrant docs (or maybe in a comment in the Vagrantfile). Given that [others](https://github.com/mitchellh/vagrant/issues/4987) have noticed this, as well, and that NFS doesn't give very informative error messages in this case, I'm guessing that I'm not the only one affected by this, and that a brief note could be helpful.

In case it's helpful, I mentioned in the Issue report linked above that the error message that NFS passes back in this case isn't particularly informative: "mount.nfs: access denied by server while mounting..." Running `systemctl status -l nfsserver.service` will show a log entry that mentions the filesystem possibly not being supported, but doesn't go into further detail than that.

If I may say here, as well, thank you for your work on this project. It's really exciting.

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1337
