### ISSUE TITLE
OverlayFS Corruption

### ISSUE THREAD

**Issue by kjvalencik** [coreos/coreos-vagrant#239]
I am mounting an ext4 data partition to `/var/lib/docker` for persisting images across `vagrant destroy; vagrant up` cycles. However, if the image is shutdown uncleanly, docker no longer works after the next `vagrant up`.

Running `vagrant halt` between cycles fixes the issue. If I use btrfs instead of ext4 for the data partition, I do not have the issue.

Sample output after corrupted data:

    core@e-coal ~ $ docker images
    REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
    <none>              <none>              6941bfcbbfca        6 weeks ago         0 B
    busybox             latest              8c2e06607696        6 weeks ago         2.43 MB

Thanks!

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1336
