### ISSUE TITLE
etcd failed to start

### ISSUE THREAD

**Issue by shayts7** [coreos/coreos-vagrant#240]
Hi All,

I'm working on Windows machine. I've installed Vagrant, used the default user-data and config.rb and run vagrant up.
I've logged into the machine and noticed that etcd failed to start.
Here is the error message from "journalctl -f":

Jun 10 11:12:40 core-01 systemd[1]: etcd2.service holdoff time over, scheduling restart.
Jun 10 11:12:40 core-01 systemd[1]: Started etcd2.
Jun 10 11:12:40 core-01 systemd[1]: Starting etcd2...
Jun 10 11:12:40 core-01 systemd[1]: Starting Network fabric for containers...
Jun 10 11:12:40 core-01 etcd2[3150]: 2015/06/10 11:12:40 etcd: listening for peers on http://172.17.8.101:2380
Jun 10 11:12:40 core-01 etcd2[3150]: 2015/06/10 11:12:40 etcd: listening for peers on http://172.17.8.101:7001
Jun 10 11:12:40 core-01 etcd2[3150]: 2015/06/10 11:12:40 etcd: listening for client requests on http://0.0.0.0:2379
Jun 10 11:12:40 core-01 etcd2[3150]: 2015/06/10 11:12:40 etcd: listening for client requests on http://0.0.0.0:4001
Jun 10 11:12:40 core-01 etcd2[3150]: 2015/06/10 11:12:40 etcdserver: datadir is valid for the 2.0.1 format
Jun 10 11:12:40 core-01 etcd2[3150]: 2015/06/10 11:12:40 etcd: stopping listening for client requests on http://0.0.0.0:4001
Jun 10 11:12:40 core-01 etcd2[3150]: 2015/06/10 11:12:40 etcd: stopping listening for client requests on http://0.0.0.0:2379
Jun 10 11:12:40 core-01 etcd2[3150]: 2015/06/10 11:12:40 etcd: stopping listening for peers on http://172.17.8.101:7001
Jun 10 11:12:40 core-01 etcd2[3150]: 2015/06/10 11:12:40 etcd: stopping listening for peers on http://172.17.8.101:2380
**Jun 10 11:12:40 core-01 etcd2[3150]: 2015/06/10 11:12:40 etcd: 13c808a7c74c4d71a83b299a72c04386 has different advertised URLs in the cluster and advertised peer URLs list**
Jun 10 11:12:40 core-01 systemd[1]: etcd2.service: main process exited, code=exited, status=1/FAILURE
Jun 10 11:12:40 core-01 systemd[1]: Unit etcd2.service entered failed state.
Jun 10 11:12:40 core-01 systemd[1]: etcd2.service failed.
Jun 10 11:12:40 core-01 etcdctl[3164]: Error:  cannot sync with the cluster using endpoints http://127.0.0.1:4001, http://127.0.0.1:2379

Any advise will be appreciated.

Thanks!
Shay

**Comment by wolske** [comment]
I am having similar problems. I was following the instructions at https://coreos.com/os/docs/latest/booting-on-vagrant.html, and
1. modifying the discovery token, 
2. setting the number of instances to 3,
3. specifying etcd2 instead of etcd
4. setting the channel to 'stable'

'vagrant up' brings up three nodes, but etcd2 isn't running on any of them.

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1335
