### ISSUE TITLE
No flannel daemon with the corers-vagrant

### ISSUE THREAD

**Issue by huikang** [coreos/coreos-vagrant#248]
Hi,
I am using this coreos-vagrant file to boot up 3 coreos nodes. I tried following the instructions at this link

https://coreos.com/docs/cluster-management/setup/flannel-config/

to run flannel daemon in the coreos host. However, it seems there is not flannel service available. Is there anything wrong? Thanks.

- Hui

**Comment by huikang** [comment]
- name: flanneld.service
      drop-ins:
        - name: 50-network-config.conf

There is no flannel daemon nor the file 50-network-config.conf.

**Comment by rajalokan** [comment]
Very old but answering for anyone landing here. 

Are you sure you are running, alpha channel. I'm using box from alpha.release.core-os.net/XXX and I can confirm flanneld service.

**Comment by cgswong** [comment]
@huikang Ensure you have something like:
`
  flannel:
    interface: $public_ipv4
    etcd_prefix: /coreos.com/network
    etcd_endpoints: http://$public_ipv4:2379
  units:
  - name: flanneld.service
    drop-ins:
    - name: 50-network-config.conf
      content: |
        [Service]
        ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "192.168.0.0/16" }'
    command: start
`

Also ensure that all Docker containers have flanneld as a dependency such as:
`
      Requires=docker.service
      Requires=flanneld.service
      After=docker.service
      After=flanneld.service
`
Otherwise the Docker deamon may sometimes start before flanneld and not use it (which means  the container IPs will not be assigned from the flannel network).

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1333
