### ISSUE TITLE
http://alpha.release.core-os.net/amd64-usr/%s/coreos_production_vagrant.json can't reach!

### ISSUE THREAD

**Issue by baiyunping333** [coreos/coreos-vagrant#253]
http://alpha.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json can't reach!
all http://alpha.release.core-os.net can't reach!

**Comment by crawford** [comment]
This works fine for me (California, US).

**Comment by baiyunping333** [comment]
I am Sorry, in China.

**Comment by baiyunping333** [comment]
How can make mirror for china?

**Comment by marineam** [comment]
Ah, yeah. Our downloads are hosted by Google and thus not currently available in China. We plan on reworking our download site soon though.

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1331
