### ISSUE TITLE
After share a folder coreos ask me a password

### ISSUE THREAD

**Issue by fernandoneto** [coreos/coreos-vagrant#255]
im have to share a folser from host to guest, but when i share it in file, when i try to ssh to coreos machine it ask me for a password. 
![captura de ecra de 2015-07-30 11 04 34](https://cloud.githubusercontent.com/assets/6515784/8980734/cc68e176-36aa-11e5-80c4-eee33c6b32ef.png)

the only password i use is from my host when i bring up the virtual machine (`vagrant up`)
![captura de ecra de 2015-07-30 11 06 40](https://cloud.githubusercontent.com/assets/6515784/8980777/18fd6c6e-36ab-11e5-9a40-9da9fbe2c2e1.png)

If i remove the shared folder then i can ssh into my coreos machine without password.

this is my configuration for shared-folder
```bash
$shared_folders = {'.' => '/home/core/'}

$shared_folders.each_with_index do |(host_folder, guest_folder), index|
        config.vm.synced_folder host_folder.to_s, guest_folder.to_s, id: "core-share%02d" % index, nfs: true, mount_options: ['nolock,vers=3,udp']
      end

```

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1330
