### ISSUE TITLE
Vagrant image is not available for libvirt provider

### ISSUE THREAD

**Issue by LalatenduMohanty** [coreos/coreos-vagrant#256]
I am a libvirt Vagrant user and wanted to check if there is any plan to provide the same.

**Comment by madharjan** [comment]
**You can try this**

Using `vagrant-libvirt` provider & `vagrant-mutate` plugin. **Note** : Install `Vagrant Version 1.7.2`

**Install `vagrant-libvirt` and `vagrant-mutate` Plugin**

Install Dependencies (for Mac)
```
brew install libvirt qemu
```

Install `vagrant-libvirt` and `vagrant-mutate`
```
vagrant plugin install vagrant-libvirt
vagrant plugin install vagrant-mutate
```
**Add Libvirt TCP Authorization**

On Libvirt Host
```
saslpasswd2 -a libvirt [username]
```
Check Libvirt Authorization
```
virsh -c qemu+tcp://[libvirt_host_ip]://system nodeinfo
```

**Convert VirtualBox box to Libvirt box**
```
vagrant box list
vagrant mutate [virtalbox_box] libvirt
```

Merge Vagrantfile and *.rb files between `libvirt` and `virtalbox` boxes

* Update `Vagrantfile`
from `~/.vagrant.d/boxes/coreos-stable/[coreos version]/virtalbox/`
to `~/.vagrant.d/boxes/coreos-stable/[coreos version]/libvirt`

* Copy `base_mac.rb`, `change_host_name.rb` and `configure_networks.rb`
from `~/.vagrant.d/boxes/coreos-stable/[coreos version]/virtualbox/`
to `~/.vagrant.d/boxes/coreos-stable/[coreos version]/libvirt`

**Setup Passwordless SSH to LibVirt Host**
```
cat ~/.ssh/id_rsa.pub | ssh [username]@[libvirt_host] "umask 0077; mkdir -p ~/.ssh; cat >> ~/.ssh/authorized_keys"
```

**Update Vagrantfile for Libvirt**

Set appropriate values for Libvirt on Vagrantfile
```
config.vm.provider :libvirt do |libvirt |
    libvirt.host = [libvirt_host]
    libvirt.connect_via_ssh = true
    libvirt.username = [username]
    libvirt.storage_pool_name = "default"

    libvirt.graphics_type = "vnc"
    libvirt.graphics_port = "-1"
    libvirt.graphics_ip = "0.0.0.0"

    #libvirt.management_network_name = "default"
    #libvirt.management_network_address = "10.0.2.0/24"
  end
```

**Vagrant up with Libvirt**

```
vagrant up --provider libvirt
```

![vagrant-libvirt-coreos](https://cloud.githubusercontent.com/assets/646387/9053886/bb272d9e-3aad-11e5-866f-e8427e08e9e7.jpg)

Vagrant with Virtualbox is `good`, Vagrant with Libvirt is `better` as it allows ones to use any old Linux box to spin-off VMs

**Big Thanks goes to** 
https://github.com/pradels/vagrant-libvirt
https://github.com/sciurus/vagrant-mutate

**Comment by indiv0** [comment]
@madharjan big, big thanks for that info!

I've been trying to get this working for a while myself and with your guide I finally got it working.

Thank you again!

**Comment by indiv0** [comment]
Would it be at all possible to integrate this functionality into the repo?

I would be willing to do it, but I'm not sure how to best handle the libvirt configuration variables as they're provider specific, and currently `config.rb` doesn't have any provider-specific variables, which seems to be intentional.

Additionally, the `vagrant-mutate` stuff seems to be incompatible with the default workflow of the Vagrantfile, and it seems that the way to correct that would be to add a libvirt-specific ebuild to [coreos/coreos-overlay](https://github.com/coreos/coreos-overlay).

Could a maintainer clarify what the preferred approach is here?

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1329
