### ISSUE TITLE
Doc needed for using my own ssh key

### ISSUE THREAD

**Issue by hbrls** [coreos/coreos-vagrant#260]
**Senario**:

I'd like to use both `vagrant ssh` and `ssh core@10.2.0.101`. By default, the former command uses `~/.vagrant.d/insecure_private_key` while the latter uses `~/.ssh/id_rsa`.

On a traditional OS, I would append `id_rsa.pub` to `core@core-01`'s `~/.ssh/authorized_keys` and all is fine. But [CoreOS regenerate that file on reboot](https://www.digitalocean.com/community/questions/coreos-forgets-authorized_keys).

**After research**

1. I'm now setting the [ssh_authorized_keys](https://coreos.com/os/docs/latest/cloud-config.html#ssh_authorized_keys) directive in the cloud config file `user-data` following the [coreos quickstart](https://coreos.com/os/docs/latest/quickstart.html#service-discovery-with-etcd):

        #cloud-config
        ssh_authorized_keys:
          - ssh-rsa AAAA...
        coreos:
            units:
        ...

2. Then modify the `Vagrantfile` to tell `vagrant ssh` to use my own private key following [vagrant doc](https://docs.vagrantup.com/v2/vagrantfile/ssh_settings.html) 

        config.ssh.insert_key = false
        config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "~/.ssh/id_rsa"]

1 is not in user-data.sample, and 2 is not in Vagrantfile. Am I on the right way? Can we elaborate on the docs?

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1327
