### ISSUE TITLE
ssh: unable to authenticate, attempted methods [none publickey]

### ISSUE THREAD

**Issue by YP28** [coreos/coreos-vagrant#261]
CoreOS stable (723.3.0) (on DigitalOcean)
fleetctl version 0.10.2

When I try to run services through fleetctl and a service get scheduled on a different CoreOS host, and I try to journal -f to that particular service I get the following error:
```
Error running remote command: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```
Both nodes are installed with a public/private keypair from my MacBook and the exact same cloud-config. Also, when I try to ssh -A core@ip to the other node, it keeps asking me for a password for the user.

The nodes both register at the discovery service successfully, and are listed when I run ```fleetctl list-machines```.

**Comment by crawford** [comment]
Are you using `-A` when you SSH into the first node?

**Comment by YP28** [comment]
@crawford, I did indeed forward my ssh agent.

**Comment by crawford** [comment]
Heh, let's move you to the right place.

**Comment by crawford** [comment]
This issue was moved to coreos/bugs#431
