### ISSUE TITLE
NoMethodError: undefined method `key?' for nil:NilClass

### ISSUE THREAD

**Issue by jmreicha** [coreos/coreos-vagrant#262]
I am receiving the following error after uncommenting the `config.rb` section for inserting a discovery token in to the `user-data` file.

```
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /Users/josh/github.com/coreos-vagrant/Vagrantfile
Line number: 25
Message: NoMethodError: undefined method `key?' for nil:NilClass
```

Details:

 * I haven't modified the Vagrantfile from its default state
 * This is on Vagrant v1.7.4
 * OSX 10.10.2

**Comment by jmreicha** [comment]
Manually adding the following fixes the error but creates a new issue.

```
update:
     reboot-strategy: 'off'
```

The `user-data` file gets rewritten and all of the files added via the `write_files` key get their permissions changed.

For example, this file should have permissions `0644` but after running a vagrant up is changed to have permissions `420`.

```
write_files:
- path: /etc/systemd/system/etcd2.service.d/30-configuration.conf
  permissions: 420
  content: |
    [Service]
    # General settings
    Environment=ETCD_NAME=etcd-config
    Environment=ETCD_VERBOSE=1
```

**Comment by indiv0** [comment]
Your initial issue is a duplicate of https://github.com/coreos/coreos-vagrant/issues/258, which is solved by (the as yet unmerged) PR https://github.com/coreos/coreos-vagrant/pull/259.

**Comment by jmreicha** [comment]
@indiv0 Thanks, the fix works for my first issue but I am still seeing the same behavior highlighted by my second comment where the permissions in the write_files section are being changed.

**Comment by indiv0** [comment]
@jmreicha that's likely to be a [coreos/coreos-cloudinit]() issue.

It looks like it might be this one: https://github.com/coreos/coreos-cloudinit/issues/328?

**Comment by jmreicha** [comment]
@indiv0 oh yep you're right.  Thank, I'll close this one as the suggested PR fixed the original issue.

**Comment by indiv0** [comment]
@jmreicha happy to have helped!
