### ISSUE TITLE
Start container with -v /var/nginx:/etc/nginx failed 

### ISSUE THREAD

**Issue by luk911** [coreos/coreos-vagrant#264]
I use 
CoreOs stable and official nginx image and try start container with this option:

docker run --name nginx_1 -v /var/nginx/conf:/etc/nginx:ro -p 80:80 -d nginx

I found this https://github.com/docker/docker/issues/5489
and this https://github.com/docker/docker/pull/5910

but don't understand how to.

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1326
