### ISSUE TITLE
Serve Vagrant box metadata file over HTTPS

### ISSUE THREAD

**Issue by jimmycuadra** [coreos/coreos-vagrant#281]
The URLs for the Vagrant box metadata (e.g. http://alpha.release.core-os.net/amd64-usr/current/coreos_production_vagrant_vmware_fusion.json) should be served over HTTPS. These files look like they're on Google Cloud Storage, because accessing that URL as-is with HTTPS offers a certificate for *.storage.googleapis.com, so perhaps using the raw googleapis.com URL instead of the core-os.net URL would be sufficient.

**Comment by crawford** [comment]
Take a look at https://github.com/coreos/bugs/issues/1032.

**Comment by jimmycuadra** [comment]
Can the URLs in the Vagrantfile be changed to use the format `https://storage.googleapis.com/alpha.release.core-os.net/amd64-usr/current/coreos_production_vagrant_vmware_fusion.json`? I think it's more important to use HTTPS than it is to have a shorter URL.

**Comment by crawford** [comment]
That sounds like a good idea. Would you mind opening a pull-request?

**Comment by jimmycuadra** [comment]
Sure thing.
