### ISSUE TITLE
Including Packer JSON in repo

### ISSUE THREAD

**Issue by kveroneau** [coreos/coreos-vagrant#285]
Do you use Packer to build these boxes, or another technology?  It would be really nice if the ability to build our own boxes with our own specifications(ie. disk sizes) were available.  I am currently needing to roll my own CoreOS box for Vagrant for a work project, as the disk size of 20G which this GitHub project provides is much much too small for our project requirements.  I searched around for an official Packer JSON, and was unable to locate one.  I tried one suggestion of resizing the VMDK using VBoxManage, however VBoxManage is unable to resize VMDKs as of version 5.x.x.

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1320
