### ISSUE TITLE
Docker socket appears to close itself

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [coreos/coreos-vagrant#287]
(This may be related to #132.)

So, after a boot of a clean installation of this project, with `$expose_docker_tcp` uncommented in `config.rb` (and no other changes), I'm seeing the following behaviour:

1. After `DOCKER_HOST='tcp://127.0.0.1:2375'`, the first `docker` command works fine:

        > docker version
        Client:
         Version:      1.10.3
         API version:  1.22
         Go version:   go1.6
         Git commit:   20f81dd
         Built:        Sat Mar 12 04:07:44 UTC 2016
         OS/Arch:      darwin/amd64

        Server:
         Version:      1.10.3
         API version:  1.22
         Go version:   go1.5.4
         Git commit:   3cd164c
         Built:
         OS/Arch:      linux/amd64

2. The *second* docker command throws up everywhere, because it receives an unexpected EOF (the socket closing unexpectedly, I'm supposing?)

        > docker version
        Client:
         Version:      1.10.3
         API version:  1.22
         Go version:   go1.6
         Git commit:   20f81dd
         Built:        Sat Mar 12 04:07:44 UTC 2016
         OS/Arch:      darwin/amd64
        An error occurred trying to connect: Get http://127.0.0.1:2375/v1.22/version: EOF

3. Subsequent `docker` commands don't believe there's a Docker daemon running at all:

        > docker version
        Clien:t
         Version:      1.10.3
         API version:  1.22
         Go version:   go1.6
         Git commit:   20f81dd
         Built:        Sat Mar 12 04:07:44 UTC 2016
         OS/Arch:      darwin/amd64
        Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Prior to `3.` above, I can `telnet 127.0.0.1 2375`; afterwards, it gives me “telnet: connect to address 127.0.0.1: Connection refused”.

This is reproducible for me across `vagrant destroy`, and after re-downloading this project, and the CoreOS box.

> `journalctl`: https://gist.github.com/ELLIOTTCABLE/0a39ecc7b49b5b80dd9a78ac79776b6d#file-1-coreos-journalctl-log
> `systemctl status docker.service`, etc: https://gist.github.com/ELLIOTTCABLE/0a39ecc7b49b5b80dd9a78ac79776b6d#file-2-coreos-systemctl-log

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1318
