### ISSUE TITLE
SystemD bug on CoreOS Vagrant boxes.

### ISSUE THREAD

**Issue by rhiann0n** [coreos/coreos-vagrant#289]
Hi there,

 I've tried four box versions of Coreos via Vagrant, as it seems I am running into a systemD bug, and I was hoping you might have some tips/solutions.

**Terminal Output**
$ sudo systemctl restart testing123.service
```
Error getting authority: Error initializing authority: Error calling StartServiceByName for org.freedesktop.PolicyKit1: Timeout was reached (g-io-error-quark, 24)
Failed to restart testing123.service: Connection timed out
See system logs and 'systemctl status testing123.service' for details.
```

**Journalctl:**
```
 systemd[1]: Assertion '*v' failed at ../systemd-229/src/core/timer.c:337, function add_random(). Aborting.
```

According to the interwebz, this is a [bug with SystemD](https://github.com/systemd/systemd/issues/2632), which seems to be affecting your CoreOS Vagrant boxes.

The following boxes have been tested to launch stuff locally with the same results from `journalctl`:
`https://alpha.release.core-os.net/amd64-usr/899.1.0/coreos_production_vagrant.box`
`https://alpha.release.core-os.net/amd64-usr/991.0.0/coreos_production_vagrant.box`
`https://alpha.release.core-os.net/amd64-usr/1032.1.0/coreos_production_vagrant.box`
`https://alpha.release.core-os.net/amd64-usr/1053.2.0/coreos_production_vagrant.box`

I am using a custom cloud config to define services that has been successfully validated via [CoreOs Validator](https://coreos.com/validate/).

Please let me know if you need more information, as I am happy to sanitize and provide.

**Comment by marineam** [comment]
This issue was moved to coreos/bugs#1308

**Comment by rhiann0n** [comment]
Thanks, @marineam
