### ISSUE TITLE
docker build reboots machine on vagrant with btrfs backend

### ISSUE THREAD

**Issue by philips** [coreos/coreos-vagrant#68]
Unable to reproduce this issue on ec2 or kvm.

```
git clone https://github.com/dotcloud/docker.git
cd docker && git checkout v0.9.1
docker build -t docker .
```

At some point the machine simply reboots. The first step is to get a serial console that I can use from vagrant.

/cc @gabrtv

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1385
